version: "3.8"

services:
  screenshot-service:
    build: .
    container_name: screenshot-service
    restart: unless-stopped
    init: true
    pids_limit: 100
    environment:
      - TZ=America/Chicago
      - PUID=106808
      - PGID=106808
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - /volume1/docker/weather-screenshots:/screenshots:rw
      - /volume1/docker/service-status:/status:rw
    mem_limit: 1g
